//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Vector2 p_default_Steering;
        
        private static SteamVR_Action_Single p_default_Throttle;
        
        private static SteamVR_Action_Boolean p_default_Fire;
        
        private static SteamVR_Action_Boolean p_default_Throttle2;
        
        private static SteamVR_Action_Boolean p_default_Back_long;
        
        private static SteamVR_Action_Boolean p_default_Recenter;
        
        private static SteamVR_Action_Boolean p_default_Back_instant;
        
        public static SteamVR_Action_Vector2 default_Steering
        {
            get
            {
                return SteamVR_Actions.p_default_Steering.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single default_Throttle
        {
            get
            {
                return SteamVR_Actions.p_default_Throttle.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Fire
        {
            get
            {
                return SteamVR_Actions.p_default_Fire.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Throttle2
        {
            get
            {
                return SteamVR_Actions.p_default_Throttle2.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Back_long
        {
            get
            {
                return SteamVR_Actions.p_default_Back_long.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Recenter
        {
            get
            {
                return SteamVR_Actions.p_default_Recenter.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Back_instant
        {
            get
            {
                return SteamVR_Actions.p_default_Back_instant.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_Steering,
                    SteamVR_Actions.default_Throttle,
                    SteamVR_Actions.default_Fire,
                    SteamVR_Actions.default_Throttle2,
                    SteamVR_Actions.default_Back_long,
                    SteamVR_Actions.default_Recenter,
                    SteamVR_Actions.default_Back_instant};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Steering,
                    SteamVR_Actions.default_Throttle,
                    SteamVR_Actions.default_Fire,
                    SteamVR_Actions.default_Throttle2,
                    SteamVR_Actions.default_Back_long,
                    SteamVR_Actions.default_Recenter,
                    SteamVR_Actions.default_Back_instant};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[0];
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_Fire,
                    SteamVR_Actions.default_Throttle2,
                    SteamVR_Actions.default_Back_long,
                    SteamVR_Actions.default_Recenter,
                    SteamVR_Actions.default_Back_instant};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Throttle};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_Steering};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Steering,
                    SteamVR_Actions.default_Throttle,
                    SteamVR_Actions.default_Fire,
                    SteamVR_Actions.default_Throttle2,
                    SteamVR_Actions.default_Back_long,
                    SteamVR_Actions.default_Recenter,
                    SteamVR_Actions.default_Back_instant};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_Steering = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/Steering")));
            SteamVR_Actions.p_default_Throttle = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Throttle")));
            SteamVR_Actions.p_default_Fire = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Fire")));
            SteamVR_Actions.p_default_Throttle2 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Throttle2")));
            SteamVR_Actions.p_default_Back_long = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Back_long")));
            SteamVR_Actions.p_default_Recenter = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Recenter")));
            SteamVR_Actions.p_default_Back_instant = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Back_instant")));
        }
    }
}
