//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Alan McGovern, Ben Motmans, Lucas Ontivero")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright Alan McGovern, Ben Motmans, Lucas Ontivero ©  2006-2014")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(".NET Library for automatic network address translation")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("Open.Nat")]
[assembly: System.Reflection.AssemblyTitleAttribute("Open.Nat")]
[assembly: System.Reflection.AssemblyVersionAttribute("2.1.0.0")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("en")]

// Generated by the MSBuild WriteCodeFragment class.

