//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Steering
        {
            get
            {
                return SteamVR_Actions.default_Steering;
            }
        }
        
        public virtual SteamVR_Action_Single Throttle
        {
            get
            {
                return SteamVR_Actions.default_Throttle;
            }
        }
        
        public virtual SteamVR_Action_Boolean Fire
        {
            get
            {
                return SteamVR_Actions.default_Fire;
            }
        }
        
        public virtual SteamVR_Action_Boolean Throttle2
        {
            get
            {
                return SteamVR_Actions.default_Throttle2;
            }
        }
        
        public virtual SteamVR_Action_Boolean Back_long
        {
            get
            {
                return SteamVR_Actions.default_Back_long;
            }
        }
        
        public virtual SteamVR_Action_Boolean Recenter
        {
            get
            {
                return SteamVR_Actions.default_Recenter;
            }
        }
        
        public virtual SteamVR_Action_Boolean Back_instant
        {
            get
            {
                return SteamVR_Actions.default_Back_instant;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose_right
        {
            get
            {
                return SteamVR_Actions.default_Pose_right;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose_left
        {
            get
            {
                return SteamVR_Actions.default_Pose_left;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose_right_tip
        {
            get
            {
                return SteamVR_Actions.default_Pose_right_tip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose_left_tip
        {
            get
            {
                return SteamVR_Actions.default_Pose_left_tip;
            }
        }
    }
}
